name: Build Windows Executable

on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pandas PyQt6 openpyxl
    
    - name: Build executable
      run: |
        pyinstaller --name="经济数据面板生成器" `
          --windowed `
          --onefile `
          --icon=icon.png `
          --add-data="styles.py;." `
          --add-data="panel_generator.py;." `
          --add-data="icon.png;." `
          --hidden-import=pandas `
          --hidden-import=PyQt6 `
          --hidden-import=openpyxl `
          main.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-executable
        path: dist/经济数据面板生成器.exe 