name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pandas PyQt6 openpyxl Pillow
    
    - name: Build executable
      run: |
        pyinstaller --name="经济数据面板生成器" `
          --windowed `
          --onefile `
          --icon=icon.ico `
          --add-data="styles.py;." `
          --add-data="panel_generator.py;." `
          --add-data="icon.ico;." `
          --hidden-import=pandas `
          --hidden-import=PyQt6 `
          --hidden-import=openpyxl `
          main.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows-executable
        path: dist/经济数据面板生成器.exe
        retention-days: 5