name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pandas PyQt6 openpyxl requests packaging
    
    - name: Build executable
      run: |
        pyinstaller --name="EconPanelMaker" `
          --windowed `
          --onefile `
          --icon=icon.ico `
          --add-data="panel_generator.py;." `
          --add-data="base_data.py;." `
          --add-data="styles.py;." `
          --add-data="updater.py;." `
          --add-data="icon.ico;." `
          --add-data="使用说明_小红书版.txt;." `
          --hidden-import=pandas `
          --hidden-import=PyQt6 `
          --hidden-import=openpyxl `
          --hidden-import=requests `
          --hidden-import=packaging `
          main.py
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: EconPanelMaker
        path: |
          dist/EconPanelMaker.exe
          使用说明_小红书版.txt
        retention-days: 5