name: Build macOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pandas PyQt6 openpyxl Pillow requests packaging
        brew install create-dmg
    
    - name: Clean build directory
      run: |
        rm -rf dist/
        rm -rf build/
    
    - name: Build app
      run: |
        pyinstaller --name="经济数据面板生成器" \
          --windowed \
          --onefile \
          --add-data="styles.py:." \
          --add-data="panel_generator.py:." \
          --add-data="updater.py:." \
          --add-data="icon.png:." \
          --hidden-import=pandas \
          --hidden-import=PyQt6 \
          --hidden-import=openpyxl \
          --hidden-import=requests \
          --hidden-import=urllib3 \
          --hidden-import=chardet \
          --hidden-import=certifi \
          --hidden-import=idna \
          --hidden-import=packaging \
          main.py
    
    - name: Create DMG
      run: |
        create-dmg \
          --volname "经济数据面板生成器" \
          --window-pos 200 120 \
          --window-size 600 400 \
          --icon-size 100 \
          --icon "经济数据面板生成器.app" 175 120 \
          --app-drop-link 425 120 \
          --no-internet-enable \
          "经济数据面板生成器.dmg" \
          "dist/经济数据面板生成器.app"
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: macos-app
        path: |
          dist/经济数据面板生成器.app
          经济数据面板生成器.dmg
        retention-days: 5